name: semgrep-check

on: [push, pull_request]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Semgrep
        run: pip install semgrep
      - name: Run Semgrep scan
        run: semgrep --config=.semgrep.yml
